[package]
name = "sugar_path"
description = "Sugar functions for manipulating paths"
repository = "https://github.com/iheyunfei/sugar_path"
version = "0.0.11"
edition = "2021"
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.4.0"

[dependencies]
once_cell = "1.9.0"

[profile.bench]
debug = true

[[bench]]
name = "normalize"
harness = false